import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { NavBar, Hero, Features, Body, Goal, MobileMenu } from "../components";
import React, { useRef, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const targetReCommunity = useRef<HTMLDivElement>(null);
  const targetRefSolution = useRef<HTMLDivElement>(null);
  const targetRefFeatures = useRef<HTMLDivElement>(null);
  const targetRefTop = useRef<HTMLDivElement>(null);
  const [isOpen, setIsOpen] = useState(false);
  const [menuToggledOn, setMenuTogglesOn] = useState(false);

  const menuToggleHandler = (data: Boolean) => {
    if (data === true) {
      setMenuTogglesOn(true);
    } else {
      setMenuTogglesOn(false);
    }
  };

  const setIsopenHandler = (data: Boolean) => {
    if (data === true) {
      setIsOpen(true);
    } else {
      setIsOpen(false);
    }
  };

  const scrollToTargetCommunity = () => {
    if (targetReCommunity.current) {
      window.scrollTo({
        top: targetReCommunity.current.offsetTop,
        behavior: "smooth",
      });
    }
  };

  const scrollToFeatures = () => {
    if (targetRefFeatures.current) {
      window.scrollTo({
        top: targetRefFeatures.current.offsetTop,
        behavior: "smooth",
      });
    }
  };

  const scrollToSolution = () => {
    if (targetRefSolution.current) {
      window.scrollTo({
        top: targetRefSolution.current.offsetTop,
        behavior: "smooth",
      });
    }
  };

  const scrollToTop = () => {
    if (targetRefTop.current) {
      window.scrollTo({
        top: targetRefTop.current.offsetTop,
        behavior: "smooth",
      });
    }
  };

  return (
    <>
      <Head>
        <title>Nitro finance || The Duality Of An AMM </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white bg-[#00040F] font-nova ">
        <div className={styles.nova}>
          <NavBar
            scrollToCommunity={scrollToTargetCommunity}
            scrollToFeatures={scrollToFeatures}
            scrollToSolution={scrollToSolution}
            menuToggleHandler={menuToggleHandler}
            setIsopenHandler={setIsopenHandler}
            isOpen={isOpen}
          />
          {menuToggledOn ? (
            <MobileMenu
              scrollToCommunity={scrollToTargetCommunity}
              scrollToFeatures={scrollToFeatures}
              scrollToSolution={scrollToSolution}
              menuToggleHandler={menuToggleHandler}
              setIsopenHandler={setIsopenHandler}
            />
          ) : (
            <>
              <Hero targetRefTop={targetRefTop} />
              <Features
                scrollToFeatures={scrollToFeatures}
                targetRefFeatures={targetRefFeatures}
              />
              <Body targetRefSolution={targetRefSolution} />
              <Goal
                targetReCommunity={targetReCommunity}
                scrollToTop={scrollToTop}
              />
            </>
          )}
        </div>
      </main>
    </>
  );
}
